-- Run this once in the Supabase SQL editor for the survey project.
-- It creates private response tables plus two public RPC functions:
-- 1. submit_full_boundary_response(...)
-- 2. update_full_boundary_feedback(...)
--
-- The public anon key can call the functions, but cannot directly read or
-- edit the response tables. Feedback updates must provide the same
-- respondent_id and write token generated by the browser at submission time.

create table if not exists public.full_boundary_responses (
  id bigint generated always as identity primary key,
  respondent_id text not null,
  write_token text not null,
  response_json jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.full_boundary_responses
  add column if not exists write_token text;

create index if not exists full_boundary_responses_respondent_id_idx
  on public.full_boundary_responses (respondent_id);

create table if not exists public.full_boundary_response_spreadsheet (
  respondent_id text primary key,
  write_token text not null,
  submitted_at timestamptz not null,
  relationship_to_wilkinsburg text,
  anchor_area text,
  years_connected text,
  final_feedback text,
  followup_email text,
  active_neighborhoods jsonb not null,
  neighborhood_count integer not null,
  neighborhood_summary text,
  neighborhood_mappings jsonb not null,
  neighborhood_rows jsonb not null,
  unassigned_block_count integer not null,
  unassigned_blocks jsonb not null,
  invalid_state_count integer not null,
  invalid_states jsonb not null,
  response_json jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.full_boundary_response_spreadsheet
  add column if not exists write_token text;

alter table public.full_boundary_response_spreadsheet
  add column if not exists final_feedback text;

alter table public.full_boundary_response_spreadsheet
  add column if not exists followup_email text;

alter table public.full_boundary_response_spreadsheet
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists full_boundary_response_spreadsheet_respondent_id_idx
  on public.full_boundary_response_spreadsheet (respondent_id);

create index if not exists full_boundary_response_spreadsheet_submitted_at_idx
  on public.full_boundary_response_spreadsheet (submitted_at);

alter table public.full_boundary_responses enable row level security;
alter table public.full_boundary_response_spreadsheet enable row level security;

drop policy if exists "Allow public survey inserts" on public.full_boundary_responses;
drop policy if exists "Allow public spreadsheet upserts" on public.full_boundary_response_spreadsheet;
drop policy if exists "Allow public spreadsheet inserts" on public.full_boundary_response_spreadsheet;
drop policy if exists "Allow public spreadsheet feedback updates" on public.full_boundary_response_spreadsheet;

create or replace function public.submit_full_boundary_response(
  p_respondent_id text,
  p_write_token text,
  p_response_json jsonb,
  p_spreadsheet_row jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if nullif(trim(p_respondent_id), '') is null then
    raise exception 'respondent_id is required';
  end if;

  if nullif(trim(p_write_token), '') is null then
    raise exception 'write_token is required';
  end if;

  insert into public.full_boundary_responses (
    respondent_id,
    write_token,
    response_json
  )
  values (
    p_respondent_id,
    p_write_token,
    p_response_json
  );

  insert into public.full_boundary_response_spreadsheet (
    respondent_id,
    write_token,
    submitted_at,
    relationship_to_wilkinsburg,
    anchor_area,
    years_connected,
    final_feedback,
    followup_email,
    active_neighborhoods,
    neighborhood_count,
    neighborhood_summary,
    neighborhood_mappings,
    neighborhood_rows,
    unassigned_block_count,
    unassigned_blocks,
    invalid_state_count,
    invalid_states,
    response_json,
    updated_at
  )
  values (
    p_respondent_id,
    p_write_token,
    coalesce((p_spreadsheet_row->>'submitted_at')::timestamptz, now()),
    p_spreadsheet_row->>'relationship_to_wilkinsburg',
    p_spreadsheet_row->>'anchor_area',
    p_spreadsheet_row->>'years_connected',
    p_spreadsheet_row->>'final_feedback',
    p_spreadsheet_row->>'followup_email',
    coalesce(p_spreadsheet_row->'active_neighborhoods', '[]'::jsonb),
    coalesce((p_spreadsheet_row->>'neighborhood_count')::integer, 0),
    p_spreadsheet_row->>'neighborhood_summary',
    coalesce(p_spreadsheet_row->'neighborhood_mappings', '{}'::jsonb),
    coalesce(p_spreadsheet_row->'neighborhood_rows', '[]'::jsonb),
    coalesce((p_spreadsheet_row->>'unassigned_block_count')::integer, 0),
    coalesce(p_spreadsheet_row->'unassigned_blocks', '[]'::jsonb),
    coalesce((p_spreadsheet_row->>'invalid_state_count')::integer, 0),
    coalesce(p_spreadsheet_row->'invalid_states', '[]'::jsonb),
    p_response_json,
    now()
  )
  on conflict (respondent_id) do update
  set
    write_token = excluded.write_token,
    submitted_at = excluded.submitted_at,
    relationship_to_wilkinsburg = excluded.relationship_to_wilkinsburg,
    anchor_area = excluded.anchor_area,
    years_connected = excluded.years_connected,
    final_feedback = excluded.final_feedback,
    followup_email = excluded.followup_email,
    active_neighborhoods = excluded.active_neighborhoods,
    neighborhood_count = excluded.neighborhood_count,
    neighborhood_summary = excluded.neighborhood_summary,
    neighborhood_mappings = excluded.neighborhood_mappings,
    neighborhood_rows = excluded.neighborhood_rows,
    unassigned_block_count = excluded.unassigned_block_count,
    unassigned_blocks = excluded.unassigned_blocks,
    invalid_state_count = excluded.invalid_state_count,
    invalid_states = excluded.invalid_states,
    response_json = excluded.response_json,
    updated_at = now();
end;
$$;

create or replace function public.update_full_boundary_feedback(
  p_respondent_id text,
  p_write_token text,
  p_final_feedback text,
  p_followup_email text,
  p_response_json jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.full_boundary_response_spreadsheet
  set
    final_feedback = p_final_feedback,
    followup_email = p_followup_email,
    response_json = p_response_json,
    updated_at = now()
  where respondent_id = p_respondent_id
    and write_token = p_write_token;

  if not found then
    raise exception 'No matching submitted response was found for this respondent.';
  end if;
end;
$$;

revoke all on public.full_boundary_responses from anon, authenticated;
revoke all on public.full_boundary_response_spreadsheet from anon, authenticated;
grant execute on function public.submit_full_boundary_response(text, text, jsonb, jsonb) to anon;
grant execute on function public.update_full_boundary_feedback(text, text, text, text, jsonb) to anon;

create or replace view public.full_boundary_response_export as
select
  respondent_id,
  submitted_at,
  relationship_to_wilkinsburg,
  anchor_area,
  years_connected,
  final_feedback,
  followup_email,
  neighborhood_count,
  neighborhood_summary,
  neighborhood_mappings,
  unassigned_block_count,
  unassigned_blocks,
  invalid_state_count,
  invalid_states,
  updated_at
from public.full_boundary_response_spreadsheet
order by submitted_at;
